### ISSUE TITLE
api报错

### ISSUE THREAD

**Issue by tackoolin** [guohuan78/AI_writing_helper#2]
未知错误，请联系开发者，错误信息：API error code 1: API接口调用已升级为异步调用，请参考使用文档：https://wenxin.baidu.com/wenxin/docs#2l6tgx5rc

**Comment by guohuan78** [comment]
已经发现这个错误，正在尝试更新软件以匹配接口，感谢反馈~

**Comment by guohuan78** [comment]
> 未知错误，请联系开发者，错误信息：API error code 1: API接口调用已升级为异步调用，请参考使用文档：https://wenxin.baidu.com/wenxin/docs#2l6tgx5rc

已经发现这个错误，正在尝试更新软件以匹配接口，感谢反馈~

**Comment by Asp0ka** [comment]
文心api正在升级，近期不会开放，等再次开放我们会更新软件。在此表示抱歉并感谢您的使用
